language: c

matrix:
  include:
  - compiler: clang
    env:
      - BUILD_METHOD=cmake
      - UBUNTU_CC_PACKAGE=clang-8
      - UPDATE_ALTER="sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 0"
  - compiler: gcc
    env:
      - BUILD_METHOD=cmake
      - UBUNTU_CC_PACKAGE=gcc-8
      - UPDATE_ALTER="sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 0"
  - compiler: clang
    env:
      - BUILD_METHOD=bmake
      - UBUNTU_CC_PACKAGE=clang-8
      - UPDATE_ALTER="sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 0"
  - compiler: gcc
    env:
      - BUILD_METHOD=bmake
      - UBUNTU_CC_PACKAGE=gcc-8
      - UPDATE_ALTER="sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 0"

dist: bionic

git:
  depth: 1

before_install:
    - sudo dpkg --add-architecture i386
    - sudo apt-get update
    - sudo apt-get upgrade -y
    - sudo apt-get install bmake "$UBUNTU_CC_PACKAGE" lib32gcc-8-dev libncurses5-dev:i386
    - test -z "$UPDATE_ALTER" || sh -c "$UPDATE_ALTER"

script:
    - if [ "$BUILD_METHOD" = "cmake" ]; then
        mkdir build;
        cd build;
        cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_C_COMPILER="$CC" ..;
        make;
        make install;
      fi
    - if [ "$BUILD_METHOD" = "bmake" ]; then
        cp sample/dreambbs.conf dreambbs.conf;
        bmake configure;
        bmake CC="$CC" all install clean;
      fi
